### ISSUE TITLE
Can't add videos to OTT in iFrame

### ISSUE THREAD

**Issue by maddie-wang** [dyc3/opentogethertube#444]
## Current Behavior
I can't add a video to an opentogethertube iframe. This impacts me since users on my site can now longer listen to music while they study. Even when I click reload frame,  I still can't add music to the queue

### How To Reproduce

1. Create an iframe of a opentogethertube site
2. Try to add a video

## Expected behavior
1. Adding a video succeeds

### Screenshots

Note: It says "Connected" at the top

![image](https://user-images.githubusercontent.com/32725368/120502370-fbf3eb00-c387-11eb-8411-aadaebe192a9.png)

![image](https://user-images.githubusercontent.com/32725368/120503069-97855b80-c388-11eb-9aaa-41a62fc5d650.png)

## Environment

- [x ] This happens on the official site: opentogethertube.com
- [ ] This happens using a self-hosted version.
    - [ ] I'm using the docker image.

### Desktop (please complete the following information when applicable):
 - OS: iOS
 - Browser chrome

@dyc3

**Comment by dyc3** [comment]
I've been able to reproduce this in production, but not locally. There's something going on that's preventing clients from getting cookies. I'll try to investigate some more after I get off work.

**Comment by dyc3** [comment]
In the meantime, if you log into an account, does it let you add videos?

**Comment by dyc3** [comment]
Reliable reproduction steps:

1. create a temporary room
2. join it
3. clear cookies
4. attempt to add a video
5. see error toast

**Comment by dyc3** [comment]
Actually, I think this could be a race condition. Here's my theory: upon a page refresh, if the websocket connection is the first request made to the server, then the cookie is not saved (because the connection remains open and cookies are saved when the request ends, i think?).

@maddie-wang have you tried refreshing the iframe, like the error message suggests?

**Comment by dyc3** [comment]
I think I fixed it. @maddie-wang can you confirm?

**Comment by maddie-wang** [comment]
@dyc3  I still have this issue

https://sesamecall.com/call/?room=random-room


![image](https://user-images.githubusercontent.com/32725368/120702040-3db08e80-c479-11eb-943b-a537f3c1fa15.png)

**Comment by dyc3** [comment]
Is your browser saving the session cookie for OTT?

**Comment by maddie-wang** [comment]
I dont think so

![image](https://user-images.githubusercontent.com/32725368/120707382-de09b180-c47f-11eb-8c94-8ee46c12df32.png)


![image](https://user-images.githubusercontent.com/32725368/120707338-cf22ff00-c47f-11eb-8b1d-0f4e1ae6b7e0.png)

![image](https://user-images.githubusercontent.com/32725368/120707352-d3e7b300-c47f-11eb-9c24-503c2c07485e.png)

**Comment by dyc3** [comment]
The `connect.sid` one is OTT's session cookie, and it's present. (We're only looking at "Cookies", not session or local storage btw) Try deleting it and try again.

**Comment by maddie-wang** [comment]
Works outside of sesame

**Comment by maddie-wang** [comment]
Doesn't work when I use Sesame 
![image](https://user-images.githubusercontent.com/32725368/120733547-09ef5c00-c4ad-11eb-8eac-46bf765689d7.png)

**Comment by maddie-wang** [comment]
I cleared cookies, and still had that error when I use sesame

**Comment by dyc3** [comment]
After a little more investigation, I think OTT's cookies are being ignored because of third party cookie restrictions imposed by browsers. We're going to have to rework authentication to fix this.
